" Filetype plugin tells matchit about pairs and probably more.
" This didn't work until I moved it before Pathogen.
filetype on
filetype indent on
filetype plugin on

" Start pathogen for managing plugins, etc.
call pathogen#infect()

" New vim
set nocompatible

" Allow hiding edited bufferes
set hidden

"" Tabs and indenting
set bs=2
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent

" Don't automatically insert linebreaks in long lines
set wrap linebreak textwidth=0

" Don't automatically show long lines wrapped
set nowrap

" Show line numbers
set number
set hlsearch

" Show $ at end of thing being changed
set cpoptions+=$

" Show status line even if single window
set laststatus=2

" Syntax highlighting
syntax enable

"" Color scheme
set background=dark
colorscheme solarized

" Misc
set wildmode=longest,list,full
set wildmenu

" Mouse support
set mouse=a
set ttymouse=xterm2   " Allows mouse dragging

" Term settings
set term=xterm-256color

" System clipboard sharing
set clipboard=unnamed

" Leader and friends
map , \

" Reselect visual area when changing indent in visual mode (from @notahat)
vnoremap < <gv
vnoremap > >gv

" AUTOMATIC SAVING 
au FocusLost * silent! wa   " FocusLost only works in GUI vim (and for CTRL-Z)
" au WinLeave,TabLeave * silent! wa
" set autowriteall   " on buffer switch

" Command-T settings
let g:CommandTMatchWindowReverse=1
let g:CommandTMaxHeight=15
map <leader>t :CommandTFlush<cr>\|:CommandT<cr>

" NERDTree settings
let g:NERDTreeChDirMode=2

" Keyboard mappings
map <Leader>n :NERDTree<CR>

